# Book settings:  https://jupyterbook.org/customize/config.html

title: Data Science Cookbook
author: Jordan Barker
logo: logo_with_text.png
exclude_patterns: ["Notebooks/Still Cooking/*"]
only_build_toc_files: true

#######################################################################################
# Execution settings
# Docs: https://jupyterbook.org/content/execute.html
execute:
    execute_notebooks: 'off'  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
    timeout: 600    # The maximum time (in seconds) each notebook cell is allowed to run.
    exclude_patterns:
    - 'parallel_processing'
    - 'time_series'

#######################################################################################
# Define the name of the latex output file for PDF builds
latex:
    latex_documents:
        targetname: book.tex

#######################################################################################
# Information about where the book exists on the web
repository:
    url: https://github.com/Jordanbarker/jordanbarker.github.io  # Online location
    path_to_book: notebook_library  # Optional path, relative to the repository root
    branch: main

#######################################################################################
# Add GitHub buttons: https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
    use_issues_button: true
    use_repository_button: true
    home_page_in_navbar: false
    favicon: 'logo.png'
    baseurl: 'jordanbarker.github.io'

#######################################################################################
sphinx:
    extra_extensions:
        - sphinxcontrib.bibtex
    config:
        html_show_copyright: false
        bibtex_reference_style: author_year
        bibtex_bibfiles:
        - references.bib