# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Data Science Cookbook
author: Jordan Barker
logo: logo_with_text.png

# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

exclude_patterns:
  - "Still Cooking/*"

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/Jordanbarker/jordanbarker.github.io  # Online location of your book
  path_to_book: notebook_library  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
