name: cookbook_env
dependencies:  
- numpy
- pandas
- scikit-learn
- scipy
- statsmodels
- lightgbm
- stumpy
- cvxpy
- pymc
- jupyter-book
- sphinxcontrib-bibtex
- seaborn
- matplotlib
- loguru
channels:  
- conda-forge